version: '2'
services:
  account-service:
      image: msa-account-server
      ports:
      - "8080:8080"
      environment:
        PROFILE: "default"
        CONFIGSERVER_URI: "http://192.168.99.100:8888"
        CONFIGSERVER_PORT: "8888"
        DATABASESERVER_PORT: "5432"