-- create table if not exists ingredient (
--     id varchar(255) not null,
--     name varchar(255) not null,
--     ingredientType varchar(255) not null
-- );
--
-- create table if not exists  taco (
--     id identity,
--     name varchar(255) not null,
--     createAt timestamp not null
-- );
--
-- create table if not exists  taco_ingredients (
--     taco bigint not null,
--     ingredient varchar(255) not null
-- );
--
-- alter table taco_ingredients add foreign key (taco) references taco(id);
-- alter table taco_ingredients add foreign key (ingredient) references ingredient(id);
--
-- create table if not exists  taco_order (
--     id identity,
--     deliveryName varchar(255) not null,
--     deliveryStreet varchar(255) not null,
--     deliveryCity varchar(255) not null,
--     deliveryState varchar(255) not null,
--     deliveryZip varchar(255) not null,
--     ccNumber varchar(255) not null,
--     ccExpiration varchar(255) not null,
--     ccCVV varchar(255) not null,
--     placedAt timestamp not null
-- );
--
-- create table if not exists taco_order_tacos (
--     tacoOrder bigint not null,
--     taco bigint not null
-- );
--
-- alter table taco_order_tacos add foreign key (tacoOrder) references taco_order(id);
-- alter table taco_order_tacos add foreign key (taco) references taco(id);