spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: study
    password: study
    url: "jdbc:postgresql://192.168.99.100:5432/study"

  jpa:
    hibernate:
      ddl-auto: update